# Generated by Django 5.1.7 on 2025-04-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_remove_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Amount',
            field=models.FloatField(default=0),
        ),
    ]
