# Generated by Django 5.2 on 2025-04-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0005_rename_amount_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Product', 'Product'), ('Travel', 'Travel'), ('Food', 'Food')], max_length=20),
        ),
    ]
