# Generated by Django 5.2 on 2025-04-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0007_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Product', 'Product'), ('Travel', 'Travel'), ('Food', 'Food')], default='Product', max_length=100),
        ),
    ]
