# Generated by Django 5.2 on 2025-05-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0009_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
