# Generated by Django 5.2 on 2025-05-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0011_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='count',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='evening_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='morning_count',
            field=models.IntegerField(default=0),
        ),
    ]
