# Generated by Django 5.2 on 2025-06-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0013_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_date']},
        ),
    ]
