# Generated by Django 5.2 on 2025-06-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0014_alter_expense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
    ]
