# Generated by Django 5.2 on 2025-06-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0015_alter_expense_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Product', 'Product'), ('service', 'service'), ('Food', 'Food')], default='Product', max_length=100),
        ),
    ]
