# Generated by Django 5.2 on 2025-06-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0016_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Product', 'Product'), ('Food', 'Food'), ('Service', 'Service')], default='Product', max_length=100),
        ),
    ]
