# Generated by Django 5.2 on 2025-07-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0019_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
